#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd & 

python3 ~/.config/scripts/initialize.py

pkill picom
	picom -f --daemon --config $HOME/.config/picom.conf &

bspc monitor -d o o o o o o o o o

bspc config border_width     		2
bspc config window_gap		 		8
bspc config normal_border_color		"#4a4c58"
bspc config focused_border_color 	"#579de7"

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox-developer-edition desktop='^2'
bspc rule -a Chromium desktop='^2'
bspc rule -a Thunar desktop='^3'
bspc rule -a Lxappearance state=floating
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
